services:
  - type: web
    name: react-file-manager
    env: node
    rootDir: abc
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html